databases:
  - name: cribbage-test-db
    plan: free
    databaseName: cribbage_test
    user: cribbage

services:
  - type: web
    name: cribbage-test-api
    runtime: docker
    dockerfilePath: ./src/Cribbage.Api/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__Cribbage
        fromDatabase: { name: cribbage-test-db, property: connectionString }
  - type: web
    name: cribbage-test-web
    runtime: docker
    dockerfilePath: ./src/Cribbage.Web/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: cribbage-test-api.onrender.com
      - key: API_SCHEME
        value: https
      - key: API_PORT
        value: "443"
  - type: web
    name: cribbage-prod-api
    runtime: docker
    dockerfilePath: ./src/Cribbage.Api/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__Cribbage
        fromDatabase: { name: cribbage-test-db, property: connectionString }
  - type: web
    name: cribbage-prod-web
    runtime: docker
    dockerfilePath: ./src/Cribbage.Web/Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: cribbage-prod-api.onrender.com
      - key: API_SCHEME
        value: https
      - key: API_PORT
        value: "443"
